In [3]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [4]:
import tensorflow as tf
from tensorflow import keras

## 8.2 TensorFlow and Keras

In [8]:
from tensorflow.keras.preprocessing.image import load_img

In [18]:
file_path = "../../clothing-dataset-small/train/t-shirt/5f0a3fa0-6a3d-4b68-b213-72766a643de7.jpg"
# Neural network expects image of certain size (usually 299^2, 224^2 or 150^2)
img = load_img(file_path, target_size=(150, 150))
# Uses PIL
# IMG consists is an array that has 3 channels (R, G, B) - each channel contains a representation of pixels with the appropriate value from this channel
# Images are encoded internally - array of image size and 3 channels - e.g. (150, 150, 3)
# Can transform PIL image into Numpy array, where each row is a pixel - [[[177 169  97], and we have 15 of them
x = np.array(img)
print(x.shape)
print(x)


(150, 150, 3)
[[[177 169  97]
  [178 169 100]
  [182 173 104]
  ...
  [251 253 250]
  [251 253 248]
  [251 254 247]]

 [[200 190 128]
  [203 193 132]
  [203 193 132]
  ...
  [250 251 246]
  [250 251 245]
  [250 251 245]]

 [[200 189 133]
  [203 192 136]
  [202 191 135]
  ...
  [253 250 245]
  [252 249 242]
  [251 248 239]]

 ...

 [[171 157  82]
  [170 156  81]
  [171 157  82]
  ...
  [184 142  32]
  [180 133  25]
  [182 135  27]]

 [[171 157  82]
  [170 156  81]
  [171 157  82]
  ...
  [187 144  32]
  [179 132  24]
  [181 134  26]]

 [[170 156  81]
  [171 157  82]
  [170 156  81]
  ...
  [184 138  26]
  [182 134  23]
  [181 133  22]]]


## 8.3 Pre-trained convolutional neural networks
- Imagenet dataset: https://www.image-net.org/
- Pre-trained models: https://keras.io/api/applications/
- Using SaturnCloud for running models in cloud - with GPU